### PR TITLE
Reorganize Packages & RoadRunner Odo

### LINKED ISSUE #5: QCR1 - Start RoadRunner Code with odometry
### QCR1 - Team Goal - Software
**Done By:** September 27, 2023
Start RoadRunner Code with odometry to provide us with progress on a new system (odo).

### PR DESCRIPTION
**Pull request by teowelton**
ahhhh fuck why is there a merge error :(

`closes #5`

### CODE REVIEW

**Review by olivia-banks — COMMENTED** [review]
Looks really nice! Should `hardware` be it's own subsystem, containing `HWC`?

**Comment by teowelton** [comment]
I wasnt going to for now, because we don't have much else to add to a "hardware" package

**Comment by olivia-banks** [comment]
That makes sense. If only we had my improved hardware class code... \s

Approving...

**Review by olivia-banks — APPROVED** [review]
Woot woot!

**Pull request merged**
