### PR TITLE
Integrate Java documentation into GitHub Pages

### LINKED ISSUE #9: QCR1 - UML Diagrams
### QCR1 - Overall Goal - Software
**Done By: September 27, 2023**
UML diagrams should be generated OR made automatically to show how our code functions.

### PR DESCRIPTION
**Pull request by olivia-banks**
Integrate Java documentation into GitHub Pages via a GitHub action. Publishing hasn't been tested since it's not on the master branch, but I see no reason why it shouldn't work.

### CODE REVIEW

**Comment by olivia-banks** [comment]
Sorry, I'll link when done.

**Comment by olivia-banks** [comment]
Nevermind then!

**Comment by olivia-banks** [comment]
Hold on, I'll enable UML diagram generation and we'll go from there.

**Comment by olivia-banks** [comment]
In theory once this gets merged into master it'll give me the option to publish to GitHub pages... _fingers crossed_! I'll squash the commits then you can review.

**Review by teowelton — APPROVED** [review]

**Pull request merged**
